### ISSUE TITLE
Leading zero in run numbers

### ISSUE THREAD

**Issue by mashephe** [JeffersonLab/hd_utilities#62] opened 2019-04-18 18:48 UTC
Hi,

For a couple weeks I've been trying to understand why a student in our group is having trouble running MCWrapper.  The symptom is that the run number used by geant(4) ends up being run 12480 even though a different run number was used in the arguments to MCWrapper and printed in the MCWrapper output to the terminal.  MC fails for 12480 due to constants problems.

We finally traced this down to typing a leading zero:  if you specify the run as 030300 you get run 12480; however, if you specify 30300 you get run 30300.

Not sure why this is a problem or where exactly the problem is... 

We went back and forth for days trying different releases, using each others setup scripts, etc.  Finally sitting down together and typing and examining every single line in the MC generation process uncovered the issue.

Matt

**Comment by markdalton** [comment] 2019-04-18 18:52
A leading zero often causes a number to be interpreted in base 8.  30300 in base 8 is 12480 in base 10.

**Comment by T-Britton** [comment] 2019-04-18 18:52
This is certainly interesting.  I have some hypothesis I will look into.....Also, for the future MCwrapper's new home is https://github.com/JeffersonLab/gluex_MCwrapper containing its own issue page :)

let me look into it and I'll try to come back with a reason

**Comment by T-Britton** [comment] 2019-04-18 18:53
@markdalton This was my top guess.  I just didn't convert it yet.  I'll try to strip leading zeroes to avoid this issue

**Comment by markito3** [comment] 2019-04-19 13:53
I opened an issue on the gluex_MCwrapper repository site referring to this one. It is [Issue 8](https://github.com/JeffersonLab/gluex_MCwrapper/issues/8) there.

**Comment by T-Britton** [comment] 2019-04-19 15:44
@mashephe does it report this number in both hdgeant and hdgeant4 for you? and is it only reported in geant incorrectly?

I am attempting to reproduce the issue and just ran hdgeant with run number 030496.  

**I can see it reports with the leading 0:** $HDDS_HOME/bin/$BMS_OSNAME/hdds-geant ccdb://GEOMETRY/main_HDDS.xml,run=030496 > tmp.F

**later:**

MZLINK.  Initialize Link Area  /GCSLNK/  for Store  0 NL/NS=   100   100
 run number        30496           1

**shows the leading 0 dropped.  JANA agrees:** JANA >>Run:30496

**however running 030496 through hdgeant4 gives:**

RUNNING GEANT4
removing Beam Photon background from geant simulation

*************************************************************
 Geant4 version Name: geant4-10-02-patch-02 [MT]   (17-June-2016)
  << in Multi-threaded mode >> 
                      Copyright : Geant4 Collaboration
                      Reference : NIM A 506 (2003), 250-303
                            WWW : http://cern.ch/geant4
*************************************************************

JANA >>Created JCalibration object of type: JCalibrationCCDB
JANA >>Generated via: JCalibration using CCDB for MySQL and SQLite databases
JANA >>Run:196

**this appears to be a base 8 problem as 9 is an invalid digit so 30496 -> 304 which converting from base 8 to 10 yields 196.  I will process the Run number inputs to remove preceding zeroes. This should protect users in either case.  I will close the issues when it is in the DEV branch and will, of course, appear in the next release.**

**Comment by mashephe** [comment] 2019-04-19 16:17
Thomas,

We were only trying in hdgeant4.  It may not be a problem with MCWrapper, but instead a "feature" of G4 (perhaps the part of G4 that is not our code).  If it is the latter case, I'd suggest MCWrapper consider "conditioning" the input to G4 to avoid exposing the feature.

Matt

---------------------------------------------------------------------
Matthew Shepherd, Professor
Department of Physics, Indiana University, Swain West 265
727 East Third Street, Bloomington, IN 47405

Office Phone:  +1 812 856 5808

**Comment by T-Britton** [comment] 2019-04-19 17:00
I agree completely.  This is what I meant by removing preceding zeroes.  A user could specify 00000030496 for all I care and MCwrapper will chop off the leading zeroes.  Everything else should see 30496 as intended.  I hopefully will implement this today

**Comment by T-Britton** [comment] 2019-04-19 17:18
A fix is in the DEV branch of gluex_MCwrapper and will be included with the next release.

**Closed by T-Britton** 2019-04-19 17:18 UTC
